# Dependencies
markdown:         redcarpet
highlighter:      'pygments'

# Permalinks
permalink:        /projects/:title

# Setup
title:            Flavio Silva
tagline:          'Things I have built'
description:      Flavio Silva. Solutions Architect at ATD. Passionate about product design.
url:              http://flaviotsf.github.io
baseurl:          '/'
paginate:         5
paginate_path:    "projects/page:num"

author:
name:            'Flavio Silva'
url:             https://twitter.com/flaviotsf

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/flaviotsf/flaviotsf.github.io
